config/routes.rb
Rails.application.routes.draw do
  resources :orders do
    resource :checkout, :controller => 'checkout' do
      member do
        get :paypal_adaptive_payment_checkout
        get :paypal_adaptive_payment
        get :paypal_adaptive_payment_confirm
        post :paypal_adaptive_payment_finish
      end
    end
  end

  match '/paypal_adaptive_payment_notify' => 'paypal_adaptive_payment_callbacks#notify', :via => [:get, :post]

  namespace :admin do
    resources :orders do
      resources :paypal_adaptive_payments do
        member do
          get :refund
          get :capture
        end
      end
    end
  end
end

app/models/billing_integration/paypal_adaptive_payment.rb
class BillingIntegration::PaypalAdaptivePayment < BillingIntegration
  preference :login, :string
  preference :password, :password
  preference :signature, :string
  preference :appid, :string
  preference :review, :boolean, :default => false
  preference :no_shipping, :boolean, :default => false
  preference :currency, :string, :default => 'USD'

  def provider_class
    # This relies on https://github.com/jpablobr/active_paypal_adaptive_payment
    ActiveMerchant::Billing::PaypalAdaptivePayment
  end

  # Spree requires this method for the profiles implementation.
  # http://spreecommerce.com/documentation/checkout.html#payment-profiles
  # def create_profile(payment); end

  # Set this to true in order to display the confirm state
  # in the checkout process...
  def payment_profiles_supported?
    false
  end

end

app/models/paypal_adaptive_payment_account.rb
# https://github.com/spree/spree_paypal_express/blob/master/app/models/paypal_account.rb
class PaypalAdaptivePaymentAccount < ActiveRecord::Base
  has_many :payments, :as => :source

  def actions
    %w{capture credit}
  end

  def capture(payment)
    authorization = find_authorization(payment)

    ap_response = payment.payment_method.provider.capture((100 * payment.amount).to_i, authorization.params["transaction"]["0"][".id"])
    if ap_response.success?
      record_log payment, ap_response
      payment.complete
    else
      gateway_error(ap_response.message)
    end

  end

  def can_capture?(payment)
    !echeck?(payment) && payment.state == "PENDING"
  end

  def credit(payment, amount=nil)
    authorization = find_capture(payment)

    amount = payment.credit_allowed >= payment.order.outstanding_balance.abs ? payment.order.outstanding_balance : payment.credit_allowed

    ap_response = payment.payment_method.provider.credit(amount.nil? ? (100 * amount).to_i : (100 * amount).to_i, authorization.params["transaction"]["0"][".id"])

    if ap_response.success?
      record_log payment, ap_response
      payment.update_attribute(:amount, payment.amount - amount)
      payment.complete
      payment.order.update!
    else
      gateway_error(ap_response.message)
    end
  end

  def can_credit?(payment)
    return false unless payment.state == "COMPLETED"
    payment.credit_allowed > 0
    !find_capture(payment).nil?
  end

  # fix for Payment#payment_profiles_supported?
  def payment_gateway
    false
  end

  def echeck?(payment)
    logs = payment.log_entries.all(:order => 'created_at DESC')
    logs.each do |log|
      details = YAML.load(log.details) # return the transaction details
      if details.params['type'] == 'echeck'
        return true
      end
    end
    return false
  end

  def record_log(payment, response)
    payment.log_entries.create(:details => response.to_yaml)
  end

  private
  def find_authorization(payment)
    logs = payment.log_entries.all(:order => 'created_at DESC')
    logs.each do |log|
      details = YAML.load(log.details) # return the transaction details
      if (details.params['status'] == 'PENDING')
        return details
      end
    end
    return nil
  end

  def find_capture(payment)
    #find the transaction associated with the original authorization/capture
    logs = payment.log_entries.all(:order => 'created_at DESC')
    logs.each do |log|
      details = YAML.load(log.details) # return the transaction details
      if details.params['status'] == 'COMPLETED'
        RETURN details
      end
    end
    return nil
  end

  def gateway_error(text)
    msg = "#{I18n.t('gateway_error')} ... #{text}"
    logger.error(msg)
    raise Spree::GatewayError.new(msg)
  end
end

app/views/admin/payments/source_forms/_paypal_adaptive_payments.html.erb
<% content_for :head do %>
  <script type="text/javascript">
    jQuery(document).ready(function(){
      $("label:contains('<%= payment_method.name %>')").hide();
      $("label:contains('<%= payment_method.name %>') input").disable();
    });
  </script>
<% end %>

app/views/admin/payments/source_views/_paypal_adaptive_payments.html.erb
<fieldset>
  <legend><%= t('paypal_account') %></legend>

  <table class="index">
    <tr>
      <th colspan="6"><%= t('account_details') %></th>
    </tr>
    <tr>
      <td><label><%= t("email") %>:</label></td>
      <td>
        <%= payment.source.email %>
      </td>
      <td><label><%= t("payer_id") %>:</label></td>
      <td>
        <%= payment.source.payer_id %>
      </td>
      <td><label><%= t("payer_country") %>:</label></td>
      <td>
        <%= payment.source.payer_country %>
      </td>
    </tr>
    <tr>
      <td><label><%= t("payer_status") %>:</label></td>
      <td colspan="5">
        <%= payment.source.payer_status %>
      </td>
    </tr>
  </table>
</fieldset>

<fieldset>
  <legend><%= t('transactions') %></legend>

  <% payment.log_entries.reverse.each do |log| %>
  <% details = YAML.load(log.details) rescue "" %>
    <table class="index">

      <% if details.is_a? ActiveMerchant::Billing::PaypalExpressResponse %>
        <tr>
          <th colspan="6"><%= t('transaction') %> <%= details.params["transaction_id"] %> -  <%= log.created_at.to_s(:date_time24) %></th>
        </tr>
        <tr>
          <td width="12%;"><label><%= t('type') %>:</label></td>
          <td width="20%;">
            <%= details.params["transaction_type"] %>
          </td>
          <td width="8%;"><label><%= t("result") %>:</label></td>
          <td width="20%;">
            <%= details.message %>
          </td>
          <td width="15%;"><label><%= t("amount") %>:</label></td>
          <td width="20%;">
            <%= number_to_currency details.params["gross_amount"] %>
          </td>
        </tr>
        <tr>
          <td><label><%= t("comment") %>:</label></td>
          <td colspan="3">
            <%= details.params["message"] %>
          </td>
          <td><label><%= t("status") %>:</label></td>
          <td>
            <%= details.params["payment_status"] %>
          </td>
        </tr>
        <% if details.params["payment_status"] == "Pending" %>
          <tr>
            <td><label><%= t("pending_reason") %>:</label></td>
            <td colspan="5">
              <%= details.params["pending_reason"] %>
            </td>
          </tr>
        <% end %>
      <% elsif details.is_a? ActiveMerchant::Billing::Integrations::Paypal::Notification %>
        <tr>
          <th colspan="6"><%= t('ipn_transaction') %> <%= details.params["txn_id"] %> -  <%= log.created_at.to_s(:date_time24) %></th>
        </tr>
        <tr>
          <td width="12%;"><label><%= t('type') %>:</label></td>
          <td width="20%;">
            <%= details.params["txn_type"] %>
          </td>
          <td width="8%;"><label><%= t("result") %>:</label></td>
          <td width="20%;">
            <%= details.params["payment_status"] %>
          </td>
          <td width="15%;"><label><%= t("amount") %>:</label></td>
          <td width="20%;">
            <%= number_to_currency details.params["mc_gross"] %>
          </td>
        </tr>
        <tr>
          <td><label><%= t("status") %>:</label></td>
          <td colspan="5">
            <%= details.params["payment_status"] %>
          </td>
        </tr>
      <% else %>
        <tr>
          <th colspan="6"><%= t('unknown_transaction') %> -  <%= log.created_at.to_s(:date_time24) %></th>
        </tr>
        <tr>
          <td colspan="6"><pre style="overflow: hidden; width:600px;"><%= log.details %></pre></th>
        </tr>

      <% end %>
    </table>
  <% end %>

</fieldset>

app/views/admin/paypal_adaptive_payments/refund.html.erb
<%= render :partial => 'admin/shared/order_tabs', :locals => {:current => "Payments"} %>

<% form_tag do %>

  <h3><%= t('refund') %></h3>
  <fieldset>
    <p>
      <label for="amount"><%= t("amount") %></label>
      <%= text_field_tag :amount, @paypal_payment.amount %>
    </p>
    <p class="form-buttons">
      <%= button t("make_refund") %>
    </p>
  </fieldset>
<% end %>

app/views/checkout/_confirm.html.erb
<fieldset id="order_details">
  <div class="clear"></div>
  <legend><%= t(@order.state, :scope => :order_state).titleize %></legend>
  <%= render :partial => 'shared/order_details', :locals => {:order => @order} %>
</fieldset>

<hr />

<div class="form-buttons">
  <input type="submit" class="continue button primary" value="<%=t("place_order") %>"/>
</div>

app/views/checkout/_delivery.html.erb
<fieldset id='shipping_method'>
  <legend><%= t("shipping_method") %></legend>
  <div class="inner">
    <div id="methods">
      <p class="field radios">
        <% @order.rate_hash.each do |shipping_method| %>
          <label>
            <%= radio_button(:order, :shipping_method_id, shipping_method[:id]) %>
            <%= shipping_method[:name] %> <%= number_to_currency shipping_method[:cost] %>
          </label><br />
        <% end %>
      </p>
    </div>
    <% if Spree::Config[:shipping_instructions] && @order.rate_hash.present? %>
      <p id="minstrs">
        <%= form.label :special_instructions, t("shipping_instructions") %><br />
        <%= form.text_area :special_instructions, :cols => 40, :rows => 7 %>
      </p>
    <% end %>
  </div>
</fieldset>

<div class="form-buttons">
  <input type="submit" class="continue button primary" value="<%=t("save_and_continue") %>"/>
</div>

app/views/checkout/_payment.html.erb
<fieldset id="payment">
  <legend><%= t("payment_information") %></legend>
  <div data-hook="checkout_payment_step">
    <% @order.available_payment_methods.each do |method| %>
    <p>
      <label>
        <%= radio_button_tag "order[payments_attributes][][payment_method_id]", method.id, method == @order.payment_method %>
        <%= t(method.name, :scope => :payment_methods, :default => method.name) %>
      </label>
    </p>
    <% end %>

    <ul id="payment-methods">
      <% @order.available_payment_methods.each do |method| %>
        <li id="payment_method_<%= method.id %>" class="<%= 'last' if method == @order.available_payment_methods.last %>">
          <fieldset>
            <%= render "checkout/payment/#{method.method_type}", :payment_method => method %>
          </fieldset>
        </li>
      <% end %>
    </ul>
    <br style='clear:both;' />
    <div data-hook="coupon_code_field"></div>
  </div>
</fieldset>

<hr class="space" />
<div class="form-buttons">
  <input type="submit" class="continue button primary" value="<%=t("save_and_continue") %>" />
</div>

app/views/checkout/edit.html.erb
<% content_for :head do %>
  <%= javascript_include_tag  'checkout', '/states' %>
<% end %>
<div id="checkout">
  <h1><%= t("checkout")%></h1>
  <%= checkout_progress %>
  <br clear="left" />
  <%= render "shared/error_messages", :target => @order %>
  <% if @order.state != 'confirm' %>
    <div id="checkout-summary" data-hook="checkout_summary_box">
      <%= render 'summary', :order => @order %>
    </div>
  <% end %>
  <%= form_for @order, :url => update_checkout_path(@order.state), :html => { :id => "checkout_form_#{@order.state}" } do |form| %>
    <%= render @order.state, :form => form %>
    <input id="post-final" type="submit" style="display:none"/>
  <% end %>
</div>

app/views/checkout/payment/_gateway.html.erb
<%= image_tag "creditcards/creditcard.gif", :id => 'creditcard-image' %>
<% param_prefix = "payment_source[#{payment_method.id}]" %>

<p class="field">
  <label for=""><%= t("card_number") %></label><br />
  <% options_hash = Rails.env.production? ? {:autocomplete => "off"} : {} %>
  <%= text_field_tag "#{param_prefix}[number]", '', options_hash.merge(:id => 'card_number', :class => 'required', :size => 19, :maxlength => 19) %>
  <span class="req">*</span>
  &nbsp;
  <span id="card_type" style="display:none;">
    ( <span id="looks_like" ><%= t('card_type_is') %> <span id="type"></span></span>
      <span id="unrecognized"><%= t('unrecognized_card_type') %></span>
    )
  </span>
</p>
<p class="field">
  <label for=""><%= t("expiration") %></label><br />
  <%= select_month(Date.today, :prefix => param_prefix, :field_name => 'month', :use_month_numbers => true, :class => 'required') %>
  <%= select_year(Date.today, :prefix => param_prefix, :field_name => 'year', :start_year => Date.today.year, :end_year => Date.today.year + 15, :class => 'required') %>
  <span class="req">*</span>
</p>
<p class="field">
  <label for=""><%= t("card_code") %></label><br />
  <%= text_field_tag "#{param_prefix}[verification_value]", '', options_hash.merge(:id => 'card_code', :class => 'required', :size => 5) %>
  <span class="req">*</span>
  <a href="/content/cvv" target="_blank" onclick="window.open(this.href,'cvv_info','left=20,top=20,width=500,height=500,toolbar=0,resizable=0,scrollbars=1');return false">
    (<%= t("whats_this") %>)
  </a>
</p>
<%= hidden_field param_prefix, 'first_name', :value => @order.billing_firstname %>
<%= hidden_field param_prefix, 'last_name',  :value => @order.billing_lastname %>

app/views/checkout/payment/_paypal_adaptive_payment.html.erb
<a href="<%= paypal_adaptive_payment_order_checkout_url @order, :payment_method_id => payment_method %>" style="text-align: center;">
  <img src="https://www.paypal.com/en_US/i/btn/btn_xpressCheckout.gif" align="left" style="margin-right:7px;"/>
</a>

app/views/checkout/payment/_paypaladaptivepayment.html.erb
<a href="<%= paypal_adaptive_payment_order_checkout_url @order, :payment_method_id => payment_method %>" style="text-align: center;">
  <img src="https://www.paypal.com/en_US/i/btn/btn_xpressCheckout.gif" align="left" style="margin-right:7px;"/>
</a>

app/views/checkout/registration.html.erb
<%= render "shared/error_messages", :target => @user %>
<h2><%= t("registration")%></h2>
<div id="registration">
  <div id="account">
    <!-- TODO: add partial with registration form -->
  </div>
  <% if Spree::Config[:allow_guest_checkout] %>
    <div id="guest_checkout">
      <%= render "shared/error_messages", :target => @order %>
      <h2><%= t(:guest_user_account) %></h2>
      <%= form_for @order, :url => update_checkout_registration_path, :html => { :method => :put, :id => "checkout_form_registration"} do |f| %>
        <p>
          <%= f.label :email, t("email") %><br />
          <%= f.text_field :email, :class => 'title'  %>
        </p>
        <p><%= submit_tag t("continue"), :class => 'button primary' %></p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_paypal_adaptive_paymetns_checkout.html.erb
<a href="<%= paypal_checkout_orders_checkout_url @checkout.order, :integration_id => integration %>" style="text-align: center;">
  <img src="https://www.paypal.com/en_US/i/btn/btn_xpressCheckout.gif" align="left" style="margin-right:7px;"/>
</a>

app/views/shared/paypal_adaptive_payments_confirm.html.erb
<h1><%= t("confirm") %></h1>
<p>
  <%= raw t("order_not_yet_placed") %>
</p>

<%= render :partial => 'shared/order_details', :locals => {:order => @order} -%>
<div class="form-buttons">
  <%= button_to t('place_order'), paypal_finish_order_checkout_url(@order, {:token => params[:token] , :PayerID => params[:PayerID], :payment_method_id =>
  params[:payment_method_id] } ), :class => "button primary" %>
</div>